[package]
name = "cosmic-themes-base16"
version = "0.1.0"
edition = "2021"

[dependencies]
ron = "0.8"
cosmic-theme = { git = "https://github.com/pop-os/libcosmic" }
cosmic-config = { git = "https://github.com/pop-os/libcosmic" }
serde = { version = "1.0", features = ["derive"]}
serde_yaml = "0.9"
